version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: todo-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: todo_db
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:

